title: SurgVLM
description: Large Vision-Language Model for Surgical Intelligence
url: https://jinlab-imvr.github.io/SurgVLM
baseurl: /SurgVLM

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .git/
  - .github/
  - node_modules/
  - vendor/ 